// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// DEBUG: log runtime env used by the client (visible in browser console)
if (typeof window !== 'undefined') {
  try {
    // eslint-disable-next-line no-console
    console.log('[Supabase] URL:', SUPABASE_URL ? 'SET' : 'MISSING');
    // eslint-disable-next-line no-console
    console.log('[Supabase] URL value:', SUPABASE_URL);
    // eslint-disable-next-line no-console
    console.log('[Supabase] KEY present:', !!SUPABASE_PUBLISHABLE_KEY);
    // eslint-disable-next-line no-console
    console.log('[Supabase] KEY value (first 20 chars):', SUPABASE_PUBLISHABLE_KEY?.substring(0, 20));

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      // eslint-disable-next-line no-console
      console.error('[Supabase] CRITICAL: Missing environment variables!');
      // eslint-disable-next-line no-console
      console.error('[Supabase] VITE_SUPABASE_URL:', SUPABASE_URL);
      // eslint-disable-next-line no-console
      console.error('[Supabase] VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY);
    }
  } catch (e) {
    // ignore logging failures
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

console.log('[Supabase] Creating client...');
export const supabase = createClient<Database>(SUPABASE_URL as string, SUPABASE_PUBLISHABLE_KEY as string);
console.log('[Supabase] Client created');

// Expose to window for debugging
if (typeof window !== 'undefined') {
  (window as any).supabase = supabase;
  console.log('[Supabase] Client exposed to window.supabase for debugging');
}